routes/web.php
<?php

use App\Http\Controllers\CatalogController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\ReviewController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('catalog', CatalogController::class);
Route::resource('country', CountryController::class);
Route::resource('review', ReviewController::class)->only('store', 'update', 'destroy');

app/Models/Catalog.php
<?php

namespace App\Models;

use App\Contracts\CatalogContract;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Catalog extends Model
{
    use HasFactory;

    protected $fillable = [CatalogContract::FIELD_NAME, CatalogContract::FIELD_PARENT_ID];

    public function children()
    {
        return $this->hasMany(Catalog::class, CatalogContract::FIELD_PARENT_ID);
    }
}

app/Models/Country.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    use HasFactory;
}

app/Models/Currency.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Currency extends Model
{
    use HasFactory;
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
}

app/Models/Review.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Review extends Model
{
    use HasFactory;

    protected $fillable = ['rating', 'comment'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CatalogController.php
<?php

namespace App\Http\Controllers;

use App\Contracts\CatalogContract;
use App\Http\Requests\CatalogRequest;
use App\Models\Catalog;

class CatalogController extends Controller
{
    public function index()
    {
        $catalogs = Catalog::whereNull('parent_id')->with('children')->get();

        // $catalogs = Catalog::paginate(15)->get();
        return view('catalogs.index', ['catalogs' => $catalogs]);
    }

    public function create()
    {
        $catalogs = Catalog::get();
        return view('catalogs.create', ['catalogs' => $catalogs]);
    }

    public function store(CatalogRequest $request)
    {

        $data = $request->validated();
        Catalog::create($data);

        return back();
    }

    public function destroy(Catalog $catalog)
    {
        $catalog->delete();

        return redirect('/');
    }

    public function edit(Catalog $catalog)
    {
        return view('catalogs.edit', compact('catalog'));
    }

    public function update(Catalog $catalog, CatalogRequest $request)
    {
        $catalog->update([$request]);

        return back();
    }


}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CountryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Country;
use Illuminate\Http\Request;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function show(Country $country)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function edit(Country $country)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Country $country)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function destroy(Country $country)
    {
        //
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ProductController extends Controller
{
    //
}

app/Http/Controllers/ReviewController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ReviewReguest;
use App\Models\Review;
use Illuminate\Http\Request;

class ReviewController extends Controller
{

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ReviewReguest $request)
    {
        $data = $request->validated();

        Review::create($data);

        return back();
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Review  $review
     * @return \Illuminate\Http\Response
     */
    public function update(ReviewReguest $request, Review $review)
    {
        $data = $request->validated();

        $review->update($data);

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Review  $review
     * @return \Illuminate\Http\Response
     */
    public function destroy(Review $review)
    {
        $review->delete();

        return redirect('/');
    }
}

resources/views/catalogs/create.blade.php
@extends('welcome')
@section('content')
    @if ($errors->any())
        <div class="alert alert-danger mt-4">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('catalog.store') }}" method="post">
        @csrf
        <div class="input-group mb-3">
            <input type="text" class="form-control mt-4" aria-label="Sizing example input" name="name" aria-describedby="inputGroup-sizing-default" placeholder="Catalog" required>
        </div>
        <select class="form-select" name="parent_id">
            <option selected value="">Null</option>
            @foreach ($catalogs as $catalog)
                <option value="{{ $catalog->id }}">
                    {{ $catalog->name }}
                </option>
            @endforeach
        </select>
        <button class="btn btn-success mt-4">CREATE</button>
    </form>
@endsection

resources/views/catalogs/index.blade.php
@extends('welcome')
@section('content')
<ul>
    @foreach ($catalogs as $catalog)
        <li>{{ $catalog->name }}</li>
        <ul>
            @foreach ($catalog->children as $subCatalog)
                <li>
                    {{ $subCatalog->name }}
                </li>
                <ul>
                    @foreach ($subCatalog->children as $subSubCatalog)
                        <li>{{ $subSubCatalog->name }}</li>
                        <ul>
                            @foreach ($subSubCatalog->children as $subSubSubCatalog)
                                    <li>{{ $subSubSubCatalog->name }}</li>
                                    <ul>
                                        @foreach ($subSubSubCatalog->children as $SsubSubSubCatalog)
                                            <li>{{ $SsubSubSubCatalog->name }}</li>
                                        @endforeach
                                    </ul>

                            @endforeach
                        </ul>
                    @endforeach

                </ul>
            @endforeach
        </ul>
    @endforeach

  </ul>
@endsection